[package]
name = "mdbook-dtmo"
version = "0.4.4-alpha.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]
description = "A combination of preprocessors for mdbook to render the Firefox Data Documentation"
license = "MPL-2.0"
homepage = "https://github.com/badboy/mdbook-dtmo"
repository = "https://github.com/badboy/mdbook-dtmo"
edition = "2018"

[dependencies]
clap = "2.33.0"
chrono = "0.4.11"
env_logger = "0.7.1"
log = "0.4.8"
mdbook = "0.3.6"
open = "1.4.0"

mdbook-mermaid = "0.2.4"
mdbook-toc = "0.2.4"
mdbook-open-on-gh = "1.1.1"

# Watch feature
notify = { version = "4.0", optional = true }
gitignore = { version = "1.0", optional = true }

# Serve feature
iron = { version = "0.6", optional = true }
staticfile = { version = "0.5", optional = true }
ws = { version = "0.9", optional = true}

[features]
default = ["watch", "serve"]
watch = ["notify", "gitignore"]
serve = ["iron", "staticfile", "ws"]
